### ISSUE TITLE
ContainerUser is Required

### ISSUE THREAD

**Issue by gitisz** [cloudbees/amazon-ecs-plugin#14]
Not sure if this goes here or [here](https://github.com/jenkinsci/amazon-ecs-plugin).  But, first wanted to say thank you for all the recent merges, especially [#46](https://github.com/jenkinsci/amazon-ecs-plugin/pull/46).

I receive the following when ContainerUser is not defined:

> com.amazonaws.services.ecs.model.ClientException: The user value contains invalid characters. Enter a value that matches the pattern ^([a-z0-9_][a-z0-9_-]{0,30})$ (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 22bb1157-3dda-11e8-8856-b952cbbe4c48)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:2701)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:2677)
	at com.amazonaws.services.ecs.AmazonECSClient.executeRegisterTaskDefinition(AmazonECSClient.java:1912)
	at com.amazonaws.services.ecs.AmazonECSClient.registerTaskDefinition(AmazonECSClient.java:1887)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:244)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback.call(ECSCloud.java:254)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback.call(ECSCloud.java:223)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

As defined in AWS, this is optional:

![image](https://user-images.githubusercontent.com/4492953/38647389-0641fb12-3dba-11e8-9358-452d3d30dce0.png)

**Comment by dimitryvolkov** [comment]
Can you try with https://github.com/jenkinsci/amazon-ecs-plugin/pull/58 ?
