### ISSUE TITLE
Override argument cannot be null

### ISSUE THREAD

**Issue by 19left** [cloudbees/amazon-ecs-plugin#17]
After build or restart of Jenkins, using a groovy script for cloud config, the first time trying to build an ECS agent results in the following stack trace:

```
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Asked to provision 1 slave(s) for: ecs-gradle
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Will provision ECS Slave ecs-gradle, for label: ecs-gradle
May 17, 2018 7:51:08 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning ECS Slave ecs-gradle from ecs-cloud with 1 executors. Remaining excess workload: 0
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService waitForSufficientClusterResources
INFO: Found 2 instances
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService waitForSufficientClusterResources
INFO: Resources found in instance arn:aws:ecs:us-east-1:*************:container-instance/**************: [{Name: CPU,Type: INTEGER,DoubleValue: 0.0,LongValue: 0,IntegerValue: 2048,StringSetValue: []}, {Name: MEMORY,Type: INTEGER,DoubleValue: 0.0,LongValue: 0,IntegerValue: 7690,StringSetValue: []}, {Name: PORTS,Type: STRINGSET,DoubleValue: 0.0,LongValue: 0,IntegerValue: 0,StringSetValue: [22, 2376, 2375, 51678, 51679]}, {Name: PORTS_UDP,Type: STRINGSET,DoubleValue: 0.0,LongValue: 0,IntegerValue: 0,StringSetValue: []}]
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService waitForSufficientClusterResources
INFO: Instance arn:aws:ecs:us-east-1:*************:container-instance/************** has 7,690mb of free memory. 256mb are required
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService waitForSufficientClusterResources
INFO: Instance arn:aws:ecs:us-east-1:*************:container-instance/************** has 2,048 units of free cpu. 1 units are required
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback call
INFO: Created Slave: ecs-cloud-175542df9ebc
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on container definition: true
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on volumes: true
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on task role: true
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback call
INFO: Running task definition arn:aws:ecs:us-east-1:******************:task-definition/ecs-cloud-ecs-gradle-git:42 on slave ecs-cloud-175542df9ebc
May 17, 2018 7:51:08 PM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback call
WARNING: Slave {0} - Cannot create ECS Task
May 17, 2018 7:51:18 PM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent ECS Slave ecs-gradle
com.amazonaws.services.ecs.model.InvalidParameterException: Override argument cannot be null. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 956cc163-5923-11e8-b02d-236ea50ec965)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:2701)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:2677)
	at com.amazonaws.services.ecs.AmazonECSClient.executeRunTask(AmazonECSClient.java:2018)
	at com.amazonaws.services.ecs.AmazonECSClient.runTask(AmazonECSClient.java:1994)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.runEcsTask(ECSService.java:268)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback.call(ECSCloud.java:255)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud$ProvisioningCallback.call(ECSCloud.java:223)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
If I go to `Manage Jenkins` -> `Configure System` and click Save, this error is not seen again, which leads me to believe some value within the plugin is not being set correctly, but the form fill corrects that. We are using Jenkins LTS 2.107.3, and I have tried plugin version 1.14 as well as building custom from `master` branch. If you need to see the groovy portion of this issue, please let me know.

**Comment by 19left** [comment]
Found the issue:  `credentialsId` was being passed in as null, when that is invalid. I changed it to `""` and I no longer got this error.
